# Generated by Django 3.2.9 on 2022-01-29 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variations',
            new_name='Variation',
        ),
    ]
